[package]
name = "NityBot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.serenity]
git = "https://github.com/DRuppFv/serenity"
default-features = false
features = []

[dependencies.tokio]
git = "https://github.com/DRuppFv/tokio"
default-features = false
features = []